# programmed by 117CS0233(Bhupati)

In [69]:
import cv2
img1=cv2.imread('1.jpg',cv2.COLOR_BGR2GRAY)
img2=cv2.imread('2.jpg',cv2.COLOR_BGR2GRAY)
img3=cv2.imread('3.jpg',cv2.COLOR_BGR2GRAY)
img4=cv2.imread('4.jpg',cv2.COLOR_BGR2GRAY)

In [72]:
#Creating (512*512) feature vector
import numpy as np
x=[]
for i in range(33,545):
    for j in range(80,592):
        x.append(np.array([img1[i,j][0],img2[i,j][0],img3[i,j][0],img4[i,j][0]]))
feature_vector=np.array(x)
feature_vector.shape

(262144, 4)

In [73]:
img1.shape

(598, 676, 3)

In [74]:
#Calculating Mean
feature_mean = np.array([feature_vector[:,0].mean(), feature_vector[:,1].mean(), feature_vector[:,2].mean(), feature_vector[:,3].mean()])
feature_mean                                                                                                                         

array([68.65904236, 72.7576828 , 68.54934692, 80.93426132])

In [75]:
#subtracting mean
feature_std=feature_vector-feature_mean.reshape(1,4)
feature_std[100000:100010]

array([[ 34.34095764,  34.2423172 ,  27.45065308, -51.93426132],
       [ 33.34095764,  31.2423172 ,  23.45065308, -51.93426132],
       [ 25.34095764,  28.2423172 ,  30.45065308, -52.93426132],
       [ 21.34095764,  28.2423172 ,  19.45065308, -52.93426132],
       [ 25.34095764,  30.2423172 ,  29.45065308, -51.93426132],
       [ 18.34095764,  30.2423172 ,  18.45065308, -50.93426132],
       [ 13.34095764,  27.2423172 ,  25.45065308, -50.93426132],
       [ 21.34095764,  23.2423172 ,  21.45065308, -50.93426132],
       [ 18.34095764,  28.2423172 ,  26.45065308, -46.93426132],
       [ 23.34095764,  22.2423172 ,  25.45065308, -50.93426132]])

In [76]:
#Calculate covariance matrix
def cov(x,y):
    l= x-x.mean()
    r=y-y.mean()
    n=x.size
    return (l*r).sum()/(n-1)
x=[]
for i in range(4):
    for j in range(4):
        x.append(cov(feature_std[:,i],feature_std[:,j]))
feature_cov = np.array(x).reshape(4,4)
feature_cov

array([[770.8225938 , 677.65579737, 698.30445073, 374.06279884],
       [677.65579737, 665.09490441, 665.22143492, 406.16333126],
       [698.30445073, 665.22143492, 774.57514276, 397.0792388 ],
       [374.06279884, 406.16333126, 397.0792388 , 900.75146056]])

In [77]:
#verify covariance matrix
np.cov(feature_std.T)

array([[770.8225938 , 677.65579737, 698.30445073, 374.06279884],
       [677.65579737, 665.09490441, 665.22143492, 406.16333126],
       [698.30445073, 665.22143492, 774.57514276, 397.0792388 ],
       [374.06279884, 406.16333126, 397.0792388 , 900.75146056]])

In [78]:
#Calculate Eigen-Values and Eigen-Vectors
w,v = np.linalg.eig(feature_cov)
#Eigen Vectors
v

array([[ 0.53377604,  0.2870481 , -0.59978322,  0.52244293],
       [ 0.50856817,  0.17611514, -0.1802647 , -0.82331434],
       [ 0.53598489,  0.24473162,  0.77945838,  0.21277046],
       [ 0.41129279, -0.90922675, -0.01446929,  0.06273439]])

In [79]:
#Eigen Values
w

array([2405.89812118,  597.10511708,   76.0225333 ,   32.21832997])

In [80]:
#Eigen Vector of img1
v[:,0]

array([0.53377604, 0.50856817, 0.53598489, 0.41129279])

In [81]:
import cv2
import numpy as np
def display_principal_components(transformed,n):
    cv2.imwrite(str(n)+'_transformed.jpg',transformed)
    img = cv2.imread(str(n)+'_transformed.jpg')
    equ = cv2.equalizeHist(img[:,:,0])
    #cv2.imshow("princial_component_"+str(n),equ)
    cv2.imwrite(str(n)+'_equalized.jpg',equ)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [82]:
import cv2
def transform_image(v,feature_std,feature_mean):
    dot=np.matmul(np.matrix.transpose(v) , np.matrix.transpose(feature_std))
    return dot.reshape(512,512)+feature_mean

#pricipal_component_1
pricipal_component_1 = transform_image(v[:,0],feature_std,feature_mean[0])
display_principal_components(pricipal_component_1,1)  

In [83]:
#pricipal_component_2
pricipal_component_2 = transform_image(v[:,1],feature_std,feature_mean[1])
display_principal_components(pricipal_component_2,2)  

In [84]:
#pricipal_component_3
pricipal_component_3 = transform_image(v[:,2],feature_std,feature_mean[2])
display_principal_components(pricipal_component_3,3)  

In [85]:
#pricipal_component_4
pricipal_component_4 = transform_image(v[:,3],feature_std,feature_mean[3])
display_principal_components(pricipal_component_4,4)  

In [86]:
#Model Verification
val=0
for i in range(4):
    val+=feature_cov[i,i]
if (val == w.sum()):
    print("Eigen values for the corresponding covariance matrix is correct. ")

Eigen values for the corresponding covariance matrix is correct. 
